Update requirements.txt
The receiver in example might failed to build due to ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)

Appending Werkzeug==2.2.2 to examples/receiver/requirements.txt helps. https://github.com/duo-labs/sharedsignals/issues/66